name: Manual Workflow

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      message:
        description: 'Please enter a message to print'
        required: true
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get file content
        run: |
          FILE_CONTENT=$(cat demo_version.txt)

      - name: echo file content
        run: |
          echo "File content: $FILE_CONTENT"

      - name: Print the message
        run: |
          echo "The message is: default"
          message=default
      - name: overwrite the message
        if: ${{ inputs.message }} != ''
        run: |
          echo "The message is: ${{ inputs.message }}"
          message=${{ inputs.message }}
      - name: display the message
        run: echo "message is $message"
