name: Manual Workflow

on:
  # 一時的にpushで動くようにする
  # pull_request:
  #   branches: master
  #   types: [closed]
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      actions: write
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get version
        id: get-version
        run: |
          version=$(cat demo_version.txt)
          echo "::set-output name=version::$version"

      - name: Push git tag
        run: |
          IMAGE_TAG=${{ steps.get-version.outputs.version }}
          CURRENT_DATE=$(date +%Y/%m/%d)
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git tag -a $IMAGE_TAG -m 'master $CURRENT_DATE'
          git push origin $IMAGE_TAG
