name: Manual Workflow

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      message:
        description: 'Please enter a message to print'
        required: true
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print the message
        run: |
          echo "The message is: default"
          message=default
      - name: overwrite the message
        if: ${{ inputs.message }} != ''
        run: |
          echo "The message is: ${{ inputs.message }}"
          message=${{ inputs.message }}
      - name: display the message
        run: echo "message is $message"
