name: Manual Workflow

on:
  pull_request:
    branches: master
    types: [closed]
  workflow_dispatch:
    inputs:
      message:
        description: 'Please enter a message to print'
        required: true
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get version
        id: get-version
        run: |
          version=$(cat demo_version.txt)
          echo "::set-output name=version::$version"

      - name: Push git tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          IMAGE_TAG=${{ steps.get-version.outputs.version }}
          CURRENT_DATE=$(date +%Y/%m/%d)
          git tag -a $IMAGE_TAG -m 'master $CURRENT_DATE'
          git push origin $IMAGE_TAG
